version: "3"

services:
  kutt:
    image: ${KUTT_IMAGE_NAME:-kutt/kutt}
    container_name: ${KUTT_CNTR_NAME:-kutt}
    build:
      context: .
      dockerfile: ${KUTT_DOCKERFILE:-Dockerfile}
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "${HOST_APP_PORT:-3000}:3000"
    env_file:
      - .env

  redis:
    image: ${REDIS_IMAGE_NAME:-redis:alpine}
    container_name: ${REDIS_CNTR_NAME:-kutt-redis}
    volumes:
      - ${REDIS_DATA_DIR:-./data/redis}:/data
    ports:
      - ${REDIS_PORT:-6397}:6379

  postgres:
    image: ${POSTGRES_IMAGE_NAME:-postgres:alpine}
    container_name: ${PG_CNTR_NAME:-kutt-postgres}
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
      POSTGRES_DB: ${DB_NAME:-kutt}
    ports:
      - ${DB_PORT:-5423}:5432
    volumes:
      - ${PG_DATA_DIR:-./data/postgres}:/var/lib/postgresql/data
